<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="loginTestSuit" duration-ms="25577" started-at="2022-10-29T12:59:24 IST" finished-at="2022-10-29T12:59:50 IST">
    <groups>
      <group name="smoke">
        <method signature="LoginPageTest.loginTest()[pri:0, instance:com.myStore.testCases.LoginPageTest@60611244]" name="loginTest" class="com.myStore.testCases.LoginPageTest"/>
      </group> <!-- smoke -->
      <group name="sanity">
        <method signature="LoginPageTest.loginTest()[pri:0, instance:com.myStore.testCases.LoginPageTest@60611244]" name="loginTest" class="com.myStore.testCases.LoginPageTest"/>
      </group> <!-- sanity -->
    </groups>
    <test name="loginValidation" duration-ms="25577" started-at="2022-10-29T12:59:24 IST" finished-at="2022-10-29T12:59:50 IST">
      <class name="com.myStore.testCases.LoginPageTest">
        <test-method status="PASS" signature="loadConfig()[pri:0, instance:com.myStore.testCases.LoginPageTest@60611244]" name="loadConfig" is-config="true" duration-ms="301" started-at="2022-10-29T12:59:24 IST" finished-at="2022-10-29T12:59:24 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfig -->
        <test-method status="PASS" signature="loginTestCase(java.lang.String)[pri:0, instance:com.myStore.testCases.LoginPageTest@60611244]" name="loginTestCase" is-config="true" duration-ms="16835" started-at="2022-10-29T12:59:24 IST" finished-at="2022-10-29T12:59:41 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestCase -->
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:com.myStore.testCases.LoginPageTest@60611244]" name="loginTest" duration-ms="8017" started-at="2022-10-29T12:59:41 IST" finished-at="2022-10-29T12:59:49 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<http://automationpractice.com/index.php?controller=authentication> but was:<http://automationpractice.com/index.php?controller=my-account>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<http://automationpractice.com/index.php?controller=authentication> but was:<http://automationpractice.com/index.php?controller=my-account>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at com.myStore.testCases.LoginPageTest.loginTest(LoginPageTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$112/239372207.accept(Unknown Source)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="close()[pri:0, instance:com.myStore.testCases.LoginPageTest@60611244]" name="close" is-config="true" duration-ms="124" started-at="2022-10-29T12:59:50 IST" finished-at="2022-10-29T12:59:50 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.myStore.testCases.LoginPageTest@60611244]" name="afterSuite" is-config="true" duration-ms="685" started-at="2022-10-29T12:59:50 IST" finished-at="2022-10-29T12:59:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.myStore.testCases.LoginPageTest -->
    </test> <!-- loginValidation -->
  </suite> <!-- loginTestSuit -->
</testng-results>
